- alias: g
  url: https://www.google.com
  command: https://www.google.com/search?q={}
  description: Search google

- alias: ddg
  url: https://www.duckduckgo.com
  command: https://duckduckgo.com/?q={}
  description: Search duckduckgo

- alias: yt
  url: https://www.youtube.com
  command: https://www.youtube.com/results?search_query={}
  description: Search youtube

- alias: b
  url: https://www.bing.com
  command: https://www.bing.com/search?q={}
  description: Search bing

- alias: w
  url: https://www.wikipedia.org/
  command: https://en.wikipedia.org/wiki/Special:Search/{}
  description: Search wikipedia

- alias: aw
  url: https://wiki.archlinux.org/
  command: https://wiki.archlinux.org/index.php?title=Special%3ASearch&search={}
  description: Search the arch wiki

- alias: def
  url: https://www.dictionary.com/
  command: https://www.dictionary.com/browse/{}?s=t
  description: Define a word with dictionary.com

- alias: wut
  url: https://www.urbandictionary.com/
  command: https://www.urbandictionary.com/define.php?term={}
  description: Searches for a phrase on urban dictionary

- alias: am
  url: https://amazon.com/
  command: https://amazon.com/s?k={}&ref=nb_sb_noss_2
  description: Search amazon

- alias: fb
  url: https://www.facebook.com/
  command: https://www.facebook.com/search/top?q={}
  description: Search Facebook

- alias: ig
  url: https://www.instagram.com/
  command: https://www.instagram.com/{}/
  description: Search instagram

- alias: li
  url: https://www.linkedin.com/
  command: https://www.linkedin.com/search/results/all/?keywords={}&origin=GLOBAL_SEARCH_HEADER
  description: Search LinkedIn

- alias: img
  url: https://images.google.com/
  command: https://images.google.com/images?um=1&hl=en&safe=active&nfpr=1&q={}
  description: Search google images

- alias: dbl
  url: http://localhost:8000/
  command: http://localhost:8000/search?q={}
  description: Forward the query to your local version of brunnylol (port 8000)

- alias: eb
  url: https://www.ebay.com/
  command: https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313&_nkw={}&_sacat=0
  description: Search ebay

- alias: maps
  url: https://www.google.com/maps
  command: https://www.google.com/maps/search/{}
  description: Search Google maps

- alias: so
  url: https://stackoverflow.com
  command: https://stackoverflow.com/search?q={}
  description: Search questions on stackoverflow

- alias: help
  url: /help
  description: Go to brunnylol's help page

- alias: bl
  url: /
  command: /search?q={}
  description: Brunnylol search

- alias: gh
  url: https://github.com
  command: https://github.com/{}
  description: Go to github repo
  encode: false
